version: 2.0

phases:
  build:
    commands:
      - mvn clean && mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=TeamSpheal_P3-BackEnd
  post_build:
    commands:
      - mv target/*.jar ./pokemondb-0.0.1-SNAPSHOT.jar

  artifacts:
    files:
      - pokemondb-0.0.1-SNAPSHOT.jar
